required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 150.5
  y: 96
  z: -15.5
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 145.5
    y: 96
    z: -18.5
    yaw: -180
    pitch: 0
  1:
    world: 'world'
    x: 155.5
    y: 96
    z: -18.5
    yaw: -180
    pitch: 0